version: '3.7'
services:
  nodejs:
    build: .docker/nodejs
    working_dir: "/app"
    ports:
      - 8100:8100
      - 35729:35729
      - 53703:53703
    volumes:
      - ./:/app
    env_file:
      - .env
    command: bash -c "sh .docker/nodejs/entrypoint.sh"